---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.68.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
        - --args=--lockfile=false
      - id: terraform_tflint
        args:
        - --args=--config=../../.tflint.hcl
